services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dentisysfront-frontend-dev:latest
    container_name: dentisysfront-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://tu-backend-url:8080/api  # Ajusta esta URL a tu backend
      - VITE_HOST=0.0.0.0
    networks:
      - app-network-dev
    command: npm run dev -- --host 0.0.0.0

networks:
  app-network-dev:
    driver: bridge
