services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dentisysfront-frontend-prod:latest
    container_name: dentisysfront-frontend-prod
    ports:
      - "8083:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://tu-backend-url/api  # Ajusta esta URL a tu backend
    networks:
      - app-network-prod
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network-prod:
    driver: bridge
