services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dentisysfront-frontend-dev:latest
    container_name: dentisysfront-frontend-dev
    ports:
      - "8092:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://tu-backend-url:8080/api
    networks:
      - app-network-dev
    restart: always

networks:
  app-network-dev:
    driver: bridge
